# Generated by Django 6.0 on 2026-01-06 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplied',
            old_name='Candidate',
            new_name='candidate',
        ),
        migrations.CreateModel(
            name='jobDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('company_address', models.TextField()),
                ('company_image', models.ImageField(null=True, upload_to='companyimage/')),
                ('job_role', models.CharField(max_length=200)),
                ('skills', models.TextField()),
                ('job_description', models.TextField()),
                ('salary_range', models.CharField(max_length=200)),
                ('experience_required', models.CharField(max_length=200)),
                ('qualification', models.CharField(max_length=200)),
                ('vacancy', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('employment_type', models.CharField(max_length=200)),
                ('industry', models.CharField(max_length=200)),
                ('job_posted', models.DateField(auto_now_add=True)),
                ('last_date', models.DateField()),
                ('hiring_process', models.TextField()),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter_app.recruiter')),
            ],
        ),
        migrations.AlterField(
            model_name='jobapplied',
            name='job_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter_app.jobdetail'),
        ),
        migrations.DeleteModel(
            name='job_Details',
        ),
    ]
