# Generated by Django 6.0 on 2026-01-06 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter_app', '0002_rename_candidate_jobapplied_candidate_jobdetail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobdetail',
            old_name='employment_type',
            new_name='employement_type',
        ),
    ]
